### ISSUE TITLE
It is not utf-8 hosts for linux and Device Name failed to attend after 127.0.0.1/1.1

### ISSUE THREAD

**Issue by aguegu** [huhamhire/huhamhire-hosts#3]
It is weird that the file structure for downloads change quite a lot.

**Comment by aguegu** [comment]
All ipv6 hosts are shitty commented.

**Comment by huhamhire** [comment]
Sorry for that. It is suggested that you need to edit these two entries in the localhost section manually with your device name of your own POSIX device. Otherwise, it may cause some problem while acquiring information from localhost.
'''
#Linux
127.0.0.1   #Replace Your Device Name Here!
127.0.1.1   #Replace Your Device Name Here!
'''

**Comment by huhamhire** [comment]
The encoding problem seems to be caused by git commitment on Windows. However, files in the zip packages is okay. I couldn't do the commit work on Linux correctly either because there is C# files in this repository. Do you have any suggestions?

**Comment by aguegu** [comment]
Thanks for reply. I strongly recommend that all hosts saved in utf-8. If a CP936 decoded hosts is needed, it can be generated by iconv by script.
